version: '3.8'

services:
  api:
    build: .
    container_name: task-api
    ports:
      - '3000:3000'
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    restart: always

  db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - '5434:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

volumes:
  pg_data:
